// State Tree
export const CLEAR_STATE = "CLEAR_STATE";

// Library Reducer
export const IMPORT_LIKES = "IMPORT_LIKES";
export const IMPORT_PLAYLISTS = "IMPORT_PLAYLISTS";
export const IMPORT_PLAYLIST_TRACKS = "IMPORT_PLAYLIST_TRACKS";
export const REMOVE_PLAYLISTS = "REMOVE_PLAYLISTS";
export const SET_NEXT_PLAYLIST_HREF = "SET_NEXT_PLAYLIST_HREF";
export const SET_PLAYLIST_SETTINGS = "SET_PLAYLIST_SETTINGS";
export const CLEAR_PLAYLIST_TRACKS = "CLEAR_PLAYLIST_TRACKS";
export const MOVE_PLAYLISTS_TO_TRASH = "MOVE_PLAYLISTS_TO_TRASH";
export const RESTORE_PLAYLISTS_FROM_TRASH = "RESTORE_PLAYLISTS_FROM_TRASH";
export const CLEAR_TRASH = "CLEAR_TRASH";
export const SET_TRACK_UNSTREAMABLE = "SET_TRACK_UNSTREAMABLE";
export const ADD_TRACK_TO_PLAYLIST = "ADD_TRACK_TO_PLAYLIST";
export const REMOVE_TRACK_FROM_PLAYLIST = "REMOVE_TRACK_FROM_PLAYLIST";
export const TOGGLE_STAR_PLAYLIST = "TOGGLE_STAR_PLAYLIST";

// User Reducer
export const SET_KORD_ID = "SET_KORD_ID";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_CONNECTION = "SET_CONNECTION";
export const SET_MAIN_CONNECTION = "SET_MAIN_CONNECTION";
export const SET_PROFILE = "SET_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const SAVE_ROUTE = "SAVE_ROUTE";
export const DEQUE_ROUTE = "DEQUE_ROUTE";
export const PUSH_LIB_ROUTE = "PUSH_LIB_ROUTE";
export const SET_SETTINGS_OPEN_STATUS = "SET_SETTINGS_OPEN_STATUS";
export const SET_SETTINGS_SOURCE = "SET_SETTINGS_SOURCE";
export const TOGGLE_ADD_TO_PLAYLIST_FORM = "TOGGLE_ADD_TO_PLAYLIST_FORM";
export const TOGGLE_DELETE_TRACK_FORM = "TOGGLE_DELETE_TRACK_FORM";
export const TOGGLE_USER_QUEUE = "TOGGLE_USER_QUEUE";
export const TOGGLE_KEYBOARD_CONTROLS_MENU = "TOGGLE_KEYBOARD_CONTROLS_MENU";
export const SET_CURRENT_TRACK_DROPDOWN = "SET_CURRENT_TRACK_DROPDOWN";

// Music Player Reducer
export const PLAY = "PLAY";
export const PAUSE = "PAUSE";
export const SEEK = "SEEK";
export const SET_PLAYER = "SET_PLAYER";
export const SET_TRACK = "SET_TRACK";
export const SET_DURATION = "SET_DURATION";
export const SET_SEEK = "SET_SEEK";
export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
export const SET_QUEUE = "SET_QUEUE";
export const SET_QUEUE_INDEX = "SET_QUEUE_INDEX";
export const ADD_TRACK_TO_USER_QUEUE = "ADD_TRACK_TO_USER_QUEUE";
export const REMOVE_TRACK_FROM_QUEUE = "REMOVE_TRACK_FROM_QUEUE";
export const SET_VOLUME = "SET_VOLUME";
export const SET_NEXT_QUEUE_HREF = "SET_NEXT_QUEUE_HREF";
export const SET_CONTEXT = "SET_CONTEXT";
export const APPEND_QUEUE = "APPEND_QUEUE";
export const SET_MUTED = "SET_MUTED";
export const PLAY_FROM_QUEUE = "PLAY_FROM_QUEUE";
export const SET_RELATED_TRACKS = "SET_RELATED_TRACKS";
export const CLEAR_REST_OF_QUEUE = "CLEAR_REST_OF_QUEUE";

// Search Reducer
export const SET_QUERY = "SET_QUERY";
export const SET_TRACK_RESULTS = "SET_TRACK_RESULTS";
export const SET_MORE_TRACK_RESULTS = "SET_MORE_TRACK_RESULTS";
export const SET_ARTIST_RESULTS = "SET_ARTIST_RESULTS";
export const ADD_TO_SEARCH_HISTORY = "ADD_TO_SEARCH_HISTORY";
export const REMOVE_FROM_SEARCH_HISTORY = "REMOVE_FROM_SEARCH_HISTORY";
export const SET_AUTOCOMPLETE_RESULTS = "SET_AUTOCOMPLETE_RESULTS";
